### ISSUE TITLE
Relations are throwing error when you use include.

### ISSUE THREAD

**Issue by kidusdev** [medz/prisma-dart#324]
Relations are not correctly converted to lists when finding user and its many posts.

```javascript
// ./prisma/schema.prisma

// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "dart run orm"
  output   = "../lib/prisma"
}

datasource db {
  provider = "sqlite"
  url      = env("DATABASE_URL")
}

model users {
  id    Int     @id @default(autoincrement())
  name  String?
  email String
  posts posts[]
}

model posts {
  id      Int    @id @default(autoincrement())
  title   String
  author  users  @relation(fields: [usersId], references: [id])
  usersId Int
}
```

``` dart
//./lib/index.dart
final prisma = PrismaClient(datasourceUrl: "file:./prisma/dev.db");

void run() async {
  final users = await prisma.users.findMany(include: UsersInclude(posts: PrismaUnion.$1(true)));

  for (var user in users) {
    print("");
    print(user.name);

    for (var post in user.posts!) {
      print("    ${post.title!}");
    }
  }
}


```

```bash
// error
Unhandled exception:
type 'MappedListIterable<dynamic, dynamic>' is not a subtype of type 'Iterable<Map<dynamic, dynamic>>?' in type cast
#0      new Users.fromJson (package:test/prisma/model.dart:44:31)
#1      UsersDelegate.findMany.<anonymous closure>.<anonymous closure> (package:test/prisma/client.dart:188:53)
#2      MappedListIterable.elementAt (dart:_internal/iterable.dart:425:31)
#3      ListIterator.moveNext (dart:_internal/iterable.dart:354:26)
#4      run (package:test/test.dart:12:20)
<asynchronous suspension>
```

```yaml
name: test
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  orm: 4.0.0-beta

dev_dependencies:
  lints: ^2.1.0
```

When i go to the library's source code i found the issues on the generated model file
```dart
// ./lib/prisma/model.dart


class Users {
  const Users({
    this.id,
    this.name,
    this.email,
    this.posts,
    this.$count,
  });

  factory Users.fromJson(Map json) => Users(
        id: json['id'],
        name: json['name'],
        email: json['email'],
         // changed this
        posts: (json['posts'] as Iterable<Map>?)?.map(_i1.Posts.fromJson),
         // into this and it worked
        // posts: (List<Map>.from(json['posts'])).map(_i1.Posts.fromJson),
        $count: json['_count'] is Map ? _i2.UsersCountOutputType.fromJson(json['_count']) : null,
      );

  final int? id;

  final String? name;

  final String? email;

  final Iterable<_i1.Posts>? posts;

  final _i2.UsersCountOutputType? $count;
}


```

**Comment by medz** [comment]
@kidusdev Please provide the version number of `orm`

**Comment by kidusdev** [comment]
@medz it is in the generated user model

**Comment by medz** [comment]
@kidusdev fix in `v4.0.0-beta.1` version https://github.com/medz/prisma-dart/releases/tag/4.0.0-beta.1

**Comment by kidusdev** [comment]
@medz wow that was fast. 👏👏👏 it is solved.

**Comment by medz** [comment]
I should thank you for providing such accurate information so that I can quickly fix it and create test code for it.

**Comment by ebwood** [comment]
If the type in .prisma is primitive list type like Int[], then the generated fromJson is also not right.
It should change from like `json['posts']` to `List.from(json['posts']`
```
model User {
	posts Int[]
}
```
