### ISSUE TITLE
orm flutter can't run

### ISSUE THREAD

**Issue by kidusdev** [medz/prisma-dart#395]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':orm_flutter:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `C:\Users\XXXX\AppData\Local\Pub\Cache\hosted\pub.dev\orm_flutter-0.1.0\android\.cxx\Debug\1j2t3s4x\arm64-v8a'
  [1/2] Generating ../../../../query_engine/arm64-v8a/libquery_engine.a
  FAILED: ../../../../query_engine/arm64-v8a/libquery_engine.a
  cmd.exe /C "cd /D C:\Users\XXXX\AppData\Local\Pub\Cache\hosted\pub.dev\orm_flutter-0.1.0 && dart run orm_flutter:dl_engine"
  Cannot operate on packages inside the cache.
  #0      fail (package:pub/src/utils.dart:575:5)
  #1      new Entrypoint (package:pub/src/entrypoint.dart:333:7)
  #2      getExecutableForCommand (package:pub/src/executable.dart:394:24)
  <asynchronous suspension>
  #3      RunCommand.run (package:dartdev/src/commands/run.dart:321:20)
  <asynchronous suspension>
  #4      CommandRunner.runCommand (package:args/command_runner.dart:212:13)
  <asynchronous suspension>
  #5      DartdevRunner.runCommand (package:dartdev/dartdev.dart:232:18)
  <asynchronous suspension>
  #6      runDartdev (package:dartdev/dartdev.dart:46:16)
  <asynchronous suspension>
  #7      main (file:///C:/b/s/w/ir/x/w/sdk/pkg/dartdev/bin/dartdev.dart:13:5)
  <asynchronous suspension>

  ninja: build stopped: subcommand failed.

  C++ build system [build] failed while executing:
      @echo off
      "C:\\Users\\XXXX\\AppData\\Local\\Android\\Sdk\\cmake\\3.18.1\\bin\\ninja.exe" ^
        -C ^
        "C:\\Users\\XXXX\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\orm_flutter-0.1.0\\android\\.cxx\\Debug\\1j2t3s4x\\arm64-v8a" ^
        orm_flutter
    from C:\Users\Kidus\AppData\Local\Pub\Cache\hosted\pub.dev\orm_flutter-0.1.0\android

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by medz** [comment]
@kidusdev Fixed, see https://prisma.pub/getting-started/flutter.html#faq

Please install：

* `orm:^5.0.1`
* `orm_flutter:^0.1.1`

**Comment by kidusdev** [comment]
@medz the previous error was resolved #395 but when i test orm: ^5.0.1 and orm_flutter: ^0.1.1 i encountered a new issue here is the stack trace


* What went wrong:
Execution failed for task ':orm_flutter:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `C:\Users\XXX\AppData\Local\Pub\Cache\hosted\pub.dev\orm_flutter-0.1.1\android\.cxx\Debug\6xj362x1\arm64-v8a'

  C++ build system [build] failed while executing:
      @echo off
      "C:\\Users\\XXXX\\AppData\\Local\\Android\\Sdk\\cmake\\3.18.1\\bin\\ninja.exe" ^
        -C ^
        "C:\\Users\\XXXX\\AppData\\Local\\Pub\\Cache\\hosted\\pub.dev\\orm_flutter-0.1.1\\android\\.cxx\\Debug\\6xj362x1\\arm64-v8a" ^
        orm_flutter
    from C:\Users\XXXX\AppData\Local\Pub\Cache\hosted\pub.dev\orm_flutter-0.1.1\android
  ninja: error: '../../../../query_engine/arm64-v8a/libquery_engine.a', needed by 'C:/Users/XXXX/PROJECTS/study/flutter/app/build/orm_flutter/intermediates/cxx/Debug/6xj362x1/obj/arm64-v8a/liborm_flutter.so', missing and no known rule to make it

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 26s
Error: Gradle task assembleDebug failed with exit code 1

**Comment by medz** [comment]
@kidusdev Run commands:

```base
flutter clean
flutter pub get
dart run orm_flutter:dl_engine
```

**Comment by medz** [comment]
https://prisma.pub/getting-started/flutter.html#not-fond-query-engine-libquery-engine-a-file

**Comment by kidusdev** [comment]
yeah i am trying to run `dart run orm_flutter:dl_engine` but it throws this error
dart run orm_flutter:dl_engine
Building package executable... 
Built orm_flutter:dl_engine.
Unhandled exception:
PathNotFoundException: Cannot open file, path = 'C:\Users\XXXX\AppData\Local\Pub\Cache\hosted\pub.dev\orm_flutter-0.1.1\.version\prisma-engines' (OS Error: The system cannot find the path specified.
, errno = 3)
#0      _File.throwIfError (dart:io/file_impl.dart:675:7)
#1      _File.openSync (dart:io/file_impl.dart:490:5)
#2      _File.readAsBytesSync (dart:io/file_impl.dart:574:18)
#3      _File.readAsStringSync (dart:io/file_impl.dart:624:18)
#4      _File.readAsLinesSync (dart:io/file_impl.dart:630:36)
#5      main (file:///C:/Users/XXXX
/AppData/Local/Pub/Cache/hosted/pub.dev/orm_flutter-0.1.1/bin/dl_engine.dart:29:8)
<asynchronous suspension>

**Comment by medz** [comment]
@kidusdev 我正在调查这个问题。

**Comment by kidusdev** [comment]
> @kidusdev 我正在调查这个问题。

Tell me how can i help?

**Comment by medz** [comment]
@kidusdev I don't have a Windows machine, and the fix is ​​all intuitive. I don't know if Windows has a Linux/macOS equivalent of `unzip`/`cp`/`tar` commands, and if the parameters are different. It would be great if you could confirm this for me.

**Comment by medz** [comment]
@kidusdev Fixed in `orm:5.0.2` and `orm_flutter:0.1.2` version

## What's Changed

* Generator regressed to previous version
* Prisma C-ABI query engine is provided by default in Flutter integration
* Flutter integration Android downloads Prisma C-ABI query engine in cmake script

**Full Changelog**: https://github.com/medz/prisma-dart/compare/orm-v5.0.2+orm_flutter-v0.1.2...orm-v5.0.2+orm_flutter-v0.1.2

**Comment by medz** [comment]
I will not close this issue for now. I need to wait for your feedback. I will close it after you confirm that there are no problems.

**Comment by kidusdev** [comment]
> I will not close this issue for now. I need to wait for your feedback. I will close it after you confirm that there are no problems

My app runs smoothly on the newer versions orm:^5.0.2 & orm_flutter: ^0.1.2 ... appreciate the fast response 👌 👍
