### ISSUE TITLE
Could not find query engine binary for current platform "android"

### ISSUE THREAD

**Issue by LucaBarden** [medz/prisma-dart#67]
I've been trying to the Prisma to work with flutter for the android platform but have been getting this error lately.

```terminal
E/flutter ( 9332): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PrismaClientInitializationError:
E/flutter ( 9332):   message: Could not find query engine binary for current platform "android" in query-engine path.
E/flutter ( 9332):
E/flutter ( 9332): This probably happens, because you built Prisma Client on a different platform.
E/flutter ( 9332):
E/flutter ( 9332): Searched Locations:
E/flutter ( 9332):   - /
E/flutter ( 9332):   - /Users/luca/Work/vertigo-app/.dart_tool/prisma
E/flutter ( 9332):
E/flutter ( 9332): You already added the platform "android" to the "generator" block in the "schema.prisma" file as described in https://pris.ly/d/client-generator, but something went wrong. That's suboptimal.
E/flutter ( 9332):
E/flutter ( 9332): Please create an issue at https://github.com/odroe/prisma-dart/issues/new
E/flutter ( 9332):   errorCode: null
E/flutter ( 9332):   clientVersion: 2.4.3
E/flutter ( 9332):
E/flutter ( 9332): #0      BinaryEngine.executable (package:orm/src/engine_core/binary/binary_engine_io.dart:198:5)
E/flutter ( 9332): <asynchronous suspension>
E/flutter ( 9332): #1      BinaryEngine._createProcess (package:orm/src/engine_core/binary/binary_engine_io.dart:355:7)
E/flutter ( 9332): <asynchronous suspension>
E/flutter ( 9332): #2      BinaryEngine.start (package:orm/src/engine_core/binary/binary_engine_io.dart:333:17)
E/flutter ( 9332): <asynchronous suspension>
E/flutter ( 9332): #3      BinaryEngine.request (package:orm/src/engine_core/binary/binary_engine_io.dart:290:5)
E/flutter ( 9332): <asynchronous suspension>
E/flutter ( 9332): #4      UserDelegate.findMany (package:eye/prisma_client.dart:46227:42)
E/flutter ( 9332): <asynchronous suspension>
E/flutter ( 9332): #5      DBManager.getUserIDs (package:eye/database/db_manager.dart:833:19)
E/flutter ( 9332): <asynchronous suspension>
E/flutter ( 9332): #6      DBManager.loginFirstUser (package:eye/database/db_manager.dart:1104:19)
E/flutter ( 9332): <asynchronous suspension>
E/flutter ( 9332):
D/SurfaceComposerClient( 9332): VRR [FRTC] client handle [bufferId:18446744073709551615 framenumber:0] [ffffffff, ffffffff]
The Flutter DevTools debugger and profiler on LE2123 is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:64567/4YgkH5OkBAY=/
E/flutter ( 9332): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PrismaClientInitializationError:
E/flutter ( 9332):   message: Could not find query engine binary for current platform "android" in query-engine path.
E/flutter ( 9332):
E/flutter ( 9332): This probably happens, because you built Prisma Client on a different platform.
E/flutter ( 9332):
E/flutter ( 9332): Searched Locations:
E/flutter ( 9332):   - /
E/flutter ( 9332):   - /Users/luca/Work/vertigo-app/.dart_tool/prisma
E/flutter ( 9332):
E/flutter ( 9332): You already added the platform "android" to the "generator" block in the "schema.prisma" file as described in https://pris.ly/d/client-generator, but something went wrong. That's suboptimal.
E/flutter ( 9332):
E/flutter ( 9332): Please create an issue at https://github.com/odroe/prisma-dart/issues/new
E/flutter ( 9332):   errorCode: null
E/flutter ( 9332):   clientVersion: 2.4.3
E/flutter ( 9332):
E/flutter ( 9332): #0      BinaryEngine.executable (package:orm/src/engine_core/binary/binary_engine_io.dart:198:5)
E/flutter ( 9332): <asynchronous suspension>
E/flutter ( 9332): #1      BinaryEngine._createProcess (package:orm/src/engine_core/binary/binary_engine_io.dart:355:7)
E/flutter ( 9332): <asynchronous suspension>
E/flutter ( 9332): #2      BinaryEngine.start (package:orm/src/engine_core/binary/binary_engine_io.dart:333:17)
E/flutter ( 9332): <asynchronous suspension>
E/flutter ( 9332): #3      BinaryEngine.request (package:orm/src/engine_core/binary/binary_engine_io.dart:290:5)
E/flutter ( 9332): <asynchronous suspension>
E/flutter ( 9332): #4      DiaryEntryDelegate.findMany (package:eye/prisma_client.dart:51066:42)
E/flutter ( 9332): <asynchronous suspension>
E/flutter ( 9332):
E/flutter ( 9332): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PrismaClientInitializationErro

```

The head of my Prisma schema looks as following:

```prisma
generator client {
  provider        = "prisma-client-dart"
  previewFeatures = ["interactiveTransactions"]
  binaryTargets   = ["linux-arm64-openssl-3.0.x"]
}

datasource db {
  provider = "sqlite"
  url      = "file:./prisma/prisma.db"
}

```

**Comment by medz** [comment]
@LucaBarden Hi, Prisma's official binary image does not provide an Android Linux engine. This feature is expected to be provided as a native Flutter plugin in a future C API version. Currently you only need to use Data Proxy engine in Android/iOS/Web.

**Comment by wasimTQ** [comment]
I tried running the simple example. Here's the error I received
`PrismaClientInitializationError:
  message: Failed to start the query engine: The remote computer refused the network connection.`

I'm positive that the same config runs on the js environment.

**Comment by wasimTQ** [comment]
And here's the error when running it on flutter app 

```
E/flutter (11681): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PrismaClientInitializationError:
E/flutter (11681):   message: Could not find query engine binary for current platform "android" in query-engine path.
E/flutter (11681):
E/flutter (11681): This probably happens, because you built Prisma Client on a different platform.
E/flutter (11681):
E/flutter (11681): Searched Locations:
E/flutter (11681):   - /
E/flutter (11681):   - .
E/flutter (11681):
E/flutter (11681): You already added the platform "android" to the "generator" block in the "schema.prisma" file as described in 
https://pris.ly/d/client-generator, but something went wrong. That's suboptimal.
E/flutter (11681):
E/flutter (11681): Please create an issue at https://github.com/odroe/prisma-dart/issues/new
E/flutter (11681):   errorCode: null
```

**Comment by TheCIash** [comment]
> And here's the error when running it on flutter app
> 
> ```
> E/flutter (11681): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PrismaClientInitializationError:
> E/flutter (11681):   message: Could not find query engine binary for current platform "android" in query-engine path.
> E/flutter (11681):
> E/flutter (11681): This probably happens, because you built Prisma Client on a different platform.
> E/flutter (11681):
> E/flutter (11681): Searched Locations:
> E/flutter (11681):   - /
> E/flutter (11681):   - .
> E/flutter (11681):
> E/flutter (11681): You already added the platform "android" to the "generator" block in the "schema.prisma" file as described in 
> https://pris.ly/d/client-generator, but something went wrong. That's suboptimal.
> E/flutter (11681):
> E/flutter (11681): Please create an issue at https://github.com/odroe/prisma-dart/issues/new
> E/flutter (11681):   errorCode: null
> ```

I have the same problem trying to run it in a flutter app.

My schema looks like this:
`generator client {
  provider = "prisma-client-dart"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}
`

**Comment by devmerz** [comment]
Same error here. any solution?

**Comment by TheCIash** [comment]
Anything on this?

**Comment by TheCIash** [comment]
Please?

**Comment by medz** [comment]
> Anything on this?

@TheCIash To be precise, the default binary Prisma engine of Prisma ORM for Dart does not support Flutter, only the Data Proxy engine supports it, and the next version will include Data Proxy in the official support. It is expected to add native Flutter support in the next major version (waiting for the release of Dart 3.0), at which time the binary engine will be abandoned or only support for pure Dart server or command-line applications will be provided. Currently the Prisma C API is still under development.

**Comment by medz** [comment]
#328
